spring.application.name=verbatime-example-jdbc-hibernate
server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/app
spring.datasource.username=app
spring.datasource.password=app

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
