package io.github.yagipass.verbatime.agent;

import io.github.yagipass.verbatime.agent.test.Check;
import io.github.yagipass.verbatime.agent.test.TestMain;
import java.util.List;

final class CorpusRoundTripTest {

  private record RoundTrip(String fixture, String expected, String libraryClass, String why) {}

  private static final List<RoundTrip> ROUND_TRIPS =
      List.of(
          new RoundTrip(
              "JacksonRoundTrip",
              "{\"id\":7,\"items\":[\"tea\",\"milk\"],\"totals\":{\"net\":3.5,\"tax\":0.35}} -> {\"id\":7,\"items\":[\"tea\",\"milk\"],\"totals\":{\"net\":3.5,\"tax\":0.35}}",
              "com/fasterxml/jackson/databind/ObjectMapper",
              "Jackson must write and bind the same JSON when jackson-databind is instrumented, since it sits on the request path of most web applications"),
          new RoundTrip(
              "KotlinRoundTrip",
              "[3, 2, 1] [[1, 2], [2, 3], [3, 4]] emitabrev 42",
              "kotlinx/coroutines/BlockingCoroutine",
              "Kotlin collections and a coroutine that suspends and resumes on another thread must give the same result instrumented, since coroutine state machines resume through code the agent rewrote"),
          new RoundTrip(
              "ScalaRoundTrip",
              "[DELTA,GAMMA,ALPHA,BETA] size=4 head=beta",
              "scala/collection/immutable/List",
              "Scala collections must build the same values instrumented, since every Scala application runs through scala-library"),
          new RoundTrip(
              "H2RoundTrip",
              "3=GAMMA;2=BETA;",
              "org/h2/command/Parser",
              "H2 must parse and run SQL the same instrumented, since its parser is among the largest, most branch-heavy methods in the corpus"),
          new RoundTrip(
              "ClojureRoundTrip",
              "3 55",
              "clojure/lang/Compiler",
              "Clojure must load its AOT-compiled core and evaluate code instrumented, since its generated bytecode looks nothing like javac's"),
          new RoundTrip(
              "GroovyRoundTrip",
              "2,4,6 emitabrev",
              "org/codehaus/groovy/control/CompilationUnit",
              "Groovy must compile and run a script instrumented, since its runtime dispatches through invokedynamic call sites bootstrapped from instrumented code"));

  private CorpusRoundTripTest() {}

  public static void main(String[] args) {
    TestMain.run("CorpusRoundTripTest", CorpusRoundTripTest::run);
    TestMain.report();
  }

  static void run() throws Exception {
    try (CorpusFixtures fx = CorpusFixtures.open()) {
      for (RoundTrip rt : ROUND_TRIPS) {
        long start = System.nanoTime();
        String original = CorpusFixtures.call(fx.original, rt.fixture(), "run");
        String transformed = CorpusFixtures.call(fx.transformed, rt.fixture(), "run");
        System.err.println(
            "[corpus] "
                + rt.fixture()
                + " -> "
                + transformed
                + " ("
                + (System.nanoTime() - start) / 1_000_000
                + " ms)");
        Check.eq(
            rt.expected(),
            original,
            rt.fixture()
                + " gives the known answer without instrumentation, so the round trip itself is sound");
        Check.eq(original, transformed, rt.why());
        Check.that(
            fx.instrumented.contains(rt.libraryClass()),
            rt.fixture()
                + " ran through an instrumented "
                + rt.libraryClass()
                + ", or it proves nothing about instrumentation");
      }
      Check.eq(
          0,
          fx.transformer.failedClasses(),
          "no class on the round trips was refused by the Transformer, so every one of them ran instrumented");
    }
  }
}
