spring.application.name=verbatime-example-kafka-consumer
server.port=8080

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=verbatime
spring.kafka.consumer.auto-offset-reset=earliest
