spring.application.name=verbatime-example-spring-batch
spring.main.web-application-type=none

spring.datasource.url=jdbc:postgresql://db:5432/app
spring.datasource.username=app
spring.datasource.password=app

spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always
