spring.application.name=verbatime-example-mybatis
server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/app
spring.datasource.username=app
spring.datasource.password=app

spring.sql.init.mode=always
mybatis.configuration.map-underscore-to-camel-case=true
