name: mvn-hash

on:
  pull_request:
    paths:
      - pom.xml
      - modules/*/pom.xml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
      - run: nix run --inputs-from . nixpkgs#nix-update -- --flake vbtm --version skip
      - run: |
          git diff --quiet && exit 0
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am 'build(nix): update vbtm mvnHash'
          git push
